---
- name: Install required packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - python3-pip
    state: present
    update_cache: yes

- name: Install Docker
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  args:
    creates: /usr/bin/docker

- name: Create project directories
  file:
    path: "{{ item }}"
    state: directory
    owner: iadmin
    group: iadmin
    mode: '0755'
  loop:
    - /home/iadmin/cicd-lab/setup/jenkins/agent
    - /opt/jenkins/jenkins_home
    - /opt/jenkins/agent

- name: Set permissions for Jenkins home
  file:
    path: /opt/jenkins/jenkins_home
    owner: 1000
    group: 1000
    recurse: yes

- name: Copy Dockerfiles and Compose
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'docker-compose.yaml.j2', dest: '/home/iadmin/cicd-lab/setup/docker-compose.yaml' }
    - { src: 'Dockerfile-jenkins.j2', dest: '/home/iadmin/cicd-lab/setup/jenkins/Dockerfile' }
    - { src: 'Dockerfile-agent.j2', dest: '/home/iadmin/cicd-lab/setup/jenkins/agent/Dockerfile' }

- name: Deploy Jenkins with Docker Compose
  community.docker.docker_compose_v2:
    project_src: /home/iadmin/cicd-lab/setup
    state: present
    build: always
