FROM jenkins/inbound-agent:latest
USER root
RUN apt-get update && \
    apt-get install -y ca-certificates curl docker.io && \
    curl -fsSL "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/kubectl && \
    usermod -aG docker jenkins || true && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
USER jenkins
